name: flutech
description: A professional Flutter developer portfolio website.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  url_launcher: ^6.1.12
  intl: ^0.19.0
  google_fonts: ^6.1.0
  url_strategy: ^0.3.0
  flutter_svg: ^2.0.7
  smooth_page_indicator: ^1.1.0
  animated_text_kit: ^4.2.2
  visibility_detector: ^0.4.0+2
  line_icons: ^2.0.3
  cached_network_image: ^3.2.3
  go_router: ^12.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - assets/images/
    - assets/images/store/
    - assets/images/store/flublocks/
    - assets/images/store/connection/
